import { useState, useEffect } from "react";
import Image from "next/image";
import styles from '../styles/Home.module.css'
import { db } from "../firebase/initFirebase";
import {
  collection,
  getDocs
} from "firebase/firestore";
import React from "react";
import Head from 'next/head'


function App() {

    const [users, setUsers] = useState([]);
    const usersCollectionRef = collection(db, "users");
    useEffect(() => {
     onSnapshot(usersCollectionRef,limit(1),(snapshot)=>{
      const getUsers = async () => {
        const data = await getDocs(usersCollectionRef);
        setUsers(data.docs.map((doc) => ({ ...doc.data(), id: doc.id })));
      };
 
      getUsers();
    });
    }, []);
 
      getUsers();
    }, []);
    return(
      <React.StrictMode>
       <Head>
        <title>Carpool web</title>
        <meta name="description" content="Generated by Capstone Group 2" />
        <link rel="icon" href="/favicon.ico" />
        
      </Head>

      {/* <main className={styles.main}> */}
      <main className="div">
        <h1 className={styles.nav} >
         TCA Carpool Overhaul
        
        </h1>  
      <div className="container">
        <Image src ="/art.jpeg" alt="" width= {100} height = {100}/>
        <h1>Art Wing &rarr;</h1>
        <style jsx>{`
        .container {
          width: 45%;
          background-color: lightgrey;
          font-family: arial;
          margin-left: 0px;
          height: 800px;
          padding: 5px 10px 10px 10px;
          border-radius: 10px;
          display: inline-block;
        }
       
      `}</style>
        { users.map((user) => {
        return (
          <div>            
            {" "}           
            {user.pickupLocation === "ArtWing" && user.isCheckedIn===true &&      
            <h1>ID: {user.id}</h1>
            }
            </div>
        );
         } )};
  
      </div>
      <div className="container2">
        <Image src ="/playground.webp" alt="" width= {100} height = {100}/>
        <h1>Playground &rarr;</h1>
        
        <style jsx>{`
        .container2 {
          width: 45%;
          background-color: lightgrey;
          font-family: arial;
          margin-left: 30px;
           height: 800px;
          padding: 5px 10px 10px 10px;
          border-radius: 10px;
          display: inline-block;
        }
       
      `}</style>
        { users.map((user) => {
        return (
          <div>            
            {" "} 
            {user.pickupLocation === "Playground" && user.isCheckedIn===true &&      
            <h1>ID: {user.id}</h1>
            }
            </div>
        );
         } )};
  
      </div>
      </main>
      </React.StrictMode>  
    );
        }
        

        

export default App;
